<a href="https://colab.research.google.com/github/Davron030901/Pandas/blob/main/NumPy_%26_Pandas_DataFrame_to_Array_Conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Pandas DataFrame'dan NumPy array'ga o'tish
Array'dan DataFrame yaratish
Index va column'larni boshqarish
Real-world use cases

```
Pandas ➜ Ma'lumotlarni yuklash, tozalash
NumPy  ➜ Matematik hisoblashlar, ML algorithms

In [ ]:
import numpy as np
import pandas as pd

```
values → eski usul, to_numpy() yangi
Index/columns ma'lumoti yo'qoladi (faqat qiymatlar)
Data type saqlanadi yoki umumiy typega convert bo'ladi

DataFrame to Array

In [ ]:
df = pd.DataFrame({'A':[1, 2, 3], 'B': [4, 5, 6]})
arr = df.values
print("Df array:", arr)

Df array: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = df.to_numpy()
print("Df array:", arr)

Df array: [[1 4]
 [2 5]
 [3 6]]


Array to DataFrame

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(arr, columns=['X', 'Y'])
print("Df array:")
print(df)

Df array:
   X  Y
0  1  2
1  3  4
2  5  6


#CSV → NumPy → Statistics

In [ ]:
data = {
    'Temperature': [23.5, 25.1, 24.8, 26.3, 25.9],
    'Humidity': [65, 70, 68, 72, 71],
    'Pressure': [1013, 1015, 1014, 1016, 1015]
}

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

DataFrame:
   Temperature  Humidity  Pressure
0         23.5        65      1013
1         25.1        70      1015
2         24.8        68      1014
3         26.3        72      1016
4         25.9        71      1015


In [ ]:
arr = df.values
print("Array:")
print(arr)

Array:
[[  23.5   65.  1013. ]
 [  25.1   70.  1015. ]
 [  24.8   68.  1014. ]
 [  26.3   72.  1016. ]
 [  25.9   71.  1015. ]]


In [ ]:
arr = df.to_numpy()
print("Array:")
print(arr)

Array:
[[  23.5   65.  1013. ]
 [  25.1   70.  1015. ]
 [  24.8   68.  1014. ]
 [  26.3   72.  1016. ]
 [  25.9   71.  1015. ]]


In [ ]:

mean = arr.mean(axis=0)
print("Mean:")
print(mean)

Mean:
[  25.12   69.2  1014.6 ]


In [ ]:
std = arr.std(axis=0)
print("Standard Deviation:")
print(std.shape)

Standard Deviation:
(3,)


In [ ]:
data = {
    'Mean': mean,
    'Std': std
}

In [ ]:
df = pd.DataFrame(data, index=['Temperature', 'Humidity', 'Pressure'])
print("DataFrame:")
print(df)

DataFrame:
                Mean       Std
Temperature    25.12  0.972420
Humidity       69.20  2.481935
Pressure     1014.60  1.019804


# Array Manipulation → DataFrame

In [ ]:
array = np.random.randint(0, 100, size=(4, 3))
print("Array:")
print(array)

min = array.min(axis=1)
max = array.max(axis=1)
mean = array.mean(axis=1)
data = {
    'Row': [0, 1, 2, 3],
    'Min': min,
    'Max': max,
    'Mean': mean
}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)

Array:
[[37 27 13]
 [59 55 26]
 [87 22  7]
 [84 12 26]]
DataFrame:
   Row  Min  Max       Mean
0    0   13   37  25.666667
1    1   26   59  46.666667
2    2    7   87  38.666667
3    3   12   84  40.666667


#Real Dataset Processing

In [ ]:
sales_data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'North', 'North', 'South', 'South', 'South'],
    'Sales': [150, 200, 175, 160, 190, 185],
    'Profit': [45, 60, 52, 48, 57, 55]
}

print("Sales Data:")
df = pd.DataFrame(sales_data)
print(df)

Sales Data:
  Product Region  Sales  Profit
0       A  North    150      45
1       B  North    200      60
2       C  North    175      52
3       A  South    160      48
4       B  South    190      57
5       C  South    185      55


In [ ]:
convert_num = df.to_numpy()
print("Convert Num:")
print(convert_num)


Convert Num:
[['A' 'North' 150 45]
 ['B' 'North' 200 60]
 ['C' 'North' 175 52]
 ['A' 'South' 160 48]
 ['B' 'South' 190 57]
 ['C' 'South' 185 55]]


In [ ]:
sales = np.array(convert_num[:, 2])
profit = np.array(convert_num[:, 3])

print("Sales:", sales)
print("Profit:", profit)

Sales: [150 200 175 160 190 185]
Profit: [45 60 52 48 57 55]


In [ ]:
profit_percentage = (profit / sales) * 100
print("Profit Percentage:")
print(profit_percentage)

Profit Percentage:
[30.0 30.0 29.714285714285715 30.0 30.0 29.72972972972973]


In [ ]:
add_df = pd.DataFrame(profit_percentage, columns=['Profit Margin'])
print("DataFrame:")
print(add_df)

DataFrame:
  Profit Margin
0          30.0
1          30.0
2     29.714286
3          30.0
4          30.0
5      29.72973


In [ ]:
all_df = pd.concat([df, add_df], axis=1)
print("DataFrame:")
print(all_df)

DataFrame:
  Product Region  Sales  Profit Profit Margin
0       A  North    150      45          30.0
1       B  North    200      60          30.0
2       C  North    175      52     29.714286
3       A  South    160      48          30.0
4       B  South    190      57          30.0
5       C  South    185      55      29.72973


In [ ]:
region = np.array(all_df['Region'])
print("Region:", region)

Region: ['North' 'North' 'North' 'South' 'South' 'South']


In [ ]:
regiaon_north = (region == 'North')
print("Region North:", regiaon_north)
regiaon_south = (region == 'South')
print("Region South:", regiaon_south)

Region North: [ True  True  True False False False]
Region South: [False False False  True  True  True]


In [ ]:
regiaon_north_profit = profit_percentage[regiaon_north]
print("Region North Profit margin:", regiaon_north_profit)
regiaon_south_profit = profit_percentage[regiaon_south]
print("Region South Profit margin:", regiaon_south_profit)
region

Region North Profit margin: [30.0 30.0 29.714285714285715]
Region South Profit margin: [30.0 30.0 29.72972972972973]


array(['North', 'North', 'North', 'South', 'South', 'South'], dtype=object)

In [ ]:
mean_north_profit = regiaon_north_profit.mean()
print("Mean Region North Profit:", mean_north_profit)
mean_south_profit = regiaon_south_profit.mean()
print("Mean Region South Profit:", mean_south_profit)

Mean Region North Profit: 29.90476190476191
Mean Region South Profit: 29.90990990990991
